выполнение 1го задания 3го урока
js-tasks-ru/js-20220613_sport11b pull request #2
Opened 2022-06-25 16:50 UTC by TraktorT330

2022-06-25 16:51 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-06-26 12:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-06-26 16:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-06-26 19:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-06-27 08:02 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const pathArray  = path.split('.'); // получаем в pathArray массив имен из пути
👍 good  лайк за замыкание

2022-06-27 08:02 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +          console.log('curr',curr);
отладочные консоли удаляйте из PR

2022-06-27 08:02 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const res = pathArray.reduce(handler,obj)
помните какой недостаток есть у `reduce` в данном решении?

2022-06-27 08:03 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  } else return undefined
напомните пожалуйста, можно ли так делать: `return undefined`

2022-06-27 08:03 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +      console.log('index', index);
логи следует удалить

2022-06-27 08:04 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +      acc[curr[1]] = curr[0];
может использовать деструктурирование для `curr[0]` и `curr[1]`?

2022-06-27 08:05 UTC, dosandk requested changes
внесите правки согласно комментариям, все отладочные консоли следует удалить

2022-06-27 09:22 UTC, TraktorT330 commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const res = pathArray.reduce(handler,obj)
К сожалению , не помню.

2022-06-27 09:23 UTC, TraktorT330 commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  } else return undefined
Убрал эту строчку в новом комите

2022-06-27 09:23 UTC, TraktorT330 commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +      console.log('index', index);
удалил

2022-06-27 09:23 UTC, TraktorT330 commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +      acc[curr[1]] = curr[0];
использовал

2022-06-27 09:23 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-06-27 15:02 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const res = pathArray.reduce(handler,obj)
`reduce` нельзя "оборвать" или другими словами выполнить `break`

2022-06-27 15:02 UTC, dosandk approved these changes
good 👍

2022-06-27 15:03 UTC, merged